import streamlit as st
import os
from dotenv import load_dotenv
from groq import Groq

# PDF
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
)
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from io import BytesIO

# ---------- LOAD ENV ----------
load_dotenv()

client = Groq(api_key=os.getenv("GROQ_API_KEY"))

# ---------- FORMAT TEXT ----------
def format_text(text):
    lines = text.split("\n")
    formatted = []

    for line in lines:
        line = line.strip()

        if not line:
            continue

        if ":" in line:
            formatted.append(f"<b>{line}</b>")
        else:
            formatted.append(f"• {line.replace('-', '').strip()}")

    return "<br/>".join(formatted)

# ---------- AI ----------
def generate_ai(prompt):
    try:
        res = client.chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=[{"role": "user", "content": prompt}]
        )
        return res.choices[0].message.content
    except Exception as e:
        return f"Error: {str(e)}"

# ---------- PDF ----------
def create_business_pdf(title, user_input, result):

    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "TitleStyle",
        parent=styles["Title"],
        textColor=colors.darkblue,
        alignment=1
    )

    heading_style = ParagraphStyle(
        "HeadingStyle",
        parent=styles["Heading2"],
        textColor=colors.darkgreen
    )

    normal = styles["Normal"]

    content = []

    # TITLE
    content.append(Paragraph(f"💼 {title}", title_style))
    content.append(Spacer(1, 20))

    # INPUT
    content.append(Paragraph("📌 Topic", heading_style))
    content.append(Spacer(1, 10))
    content.append(Paragraph(user_input, normal))
    content.append(Spacer(1, 20))

    # SUMMARY TABLE
    table_data = [
        ["Field", "Value"],
        ["Topic", user_input],
        ["Report Type", title]
    ]

    table = Table(table_data, colWidths=[150, 250])

    table.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), colors.grey),
        ("TEXTCOLOR",(0,0),(-1,0),colors.white),
        ("GRID", (0,0), (-1,-1), 1, colors.black),
        ("BACKGROUND", (0,1), (-1,-1), colors.beige)
    ]))

    content.append(Paragraph("📊 Summary", heading_style))
    content.append(Spacer(1, 10))
    content.append(table)
    content.append(Spacer(1, 20))

    # FORMATTED RESULT
    formatted_result = format_text(result)

    content.append(Paragraph("🤖 AI Analysis", heading_style))
    content.append(Spacer(1, 10))
    content.append(Paragraph(formatted_result, normal))
    content.append(Spacer(1, 20))

    # FOOTER
    content.append(Paragraph(
        "Generated by AI Business Platform",
        ParagraphStyle("footer", alignment=1, textColor=colors.grey)
    ))

    doc.build(content)
    buffer.seek(0)

    return buffer

# ---------- UI ----------
def business_ui():
    st.title("💼 AI Business Toolkit")

    option = st.selectbox(
        "Choose Tool",
        [
            "💡 Idea Generator",
            "🧾 Business Plan",
            "📊 Market Trend",
            "🧠 Competitor Analysis"
        ]
    )

    user_input = st.text_input("Enter idea / company / industry")

    if st.button("Generate", key="biz_generate"):

        if not user_input:
            st.warning("Please enter input")
            return

        # ---------- STRUCTURED PROMPTS ----------
        if option == "💡 Idea Generator":
            prompt = f"""
            Generate a business idea for {user_input}.

            STRICT FORMAT:

            Executive Summary:
            - point
            - point

            Target Audience:
            - point
            - point

            Revenue Model:
            - point
            - point

            Startup Cost:
            - point
            - point

            Keep it concise.
            """

        elif option == "🧾 Business Plan":
            prompt = f"""
            Create a business plan for {user_input}.

            STRICT FORMAT:

            Executive Summary:
            - point

            Market Analysis:
            - point

            Revenue Model:
            - point

            Growth Strategy:
            - point

            Keep it concise.
            """

        elif option == "📊 Market Trend":
            prompt = f"""
            Analyze market trends for {user_input}.

            STRICT FORMAT:

            Growth:
            - point

            Demand:
            - point

            Future Scope:
            - point

            Risks:
            - point

            Keep it concise.
            """

        else:
            prompt = f"""
            Analyze competitors for {user_input}.

            STRICT FORMAT:

            Competitors:
            - point

            Strengths:
            - point

            Weaknesses:
            - point

            Keep it concise.
            """

        # ---------- AI ----------
        with st.spinner("Generating insights..."):
            result = generate_ai(prompt)

        # ---------- UI DISPLAY ----------
        st.subheader("📊 Result")
        st.markdown(format_text(result), unsafe_allow_html=True)

        # ---------- PDF ----------
        pdf = create_business_pdf(option, user_input, result)

        st.download_button(
            "📄 Download Professional Report",
            pdf,
            file_name="business_report.pdf"
        )