import streamlit as st
import requests
import yfinance as yf
from datetime import date
import numpy as np
import os
from dotenv import load_dotenv
from groq import Groq

# PDF + Charts
import matplotlib.pyplot as plt
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Image, Spacer, Table, TableStyle
)
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from io import BytesIO

# ---------- LOAD ENV ----------
load_dotenv()

FINNHUB_API_KEY = os.getenv("FINNHUB_API_KEY")
client = Groq(api_key=os.getenv("GROQ_API_KEY"))

# ---------- SEARCH ----------
def search_tickers(query):
    url = f"https://finnhub.io/api/v1/search?q={query.upper()}&token={FINNHUB_API_KEY}"
    try:
        r = requests.get(url)
        if r.status_code == 200:
            return r.json().get("result", [])
    except:
        pass
    return []

# ---------- RSI ----------
def calculate_rsi(data):
    delta = data['Close'].diff()
    gain = delta.clip(lower=0)
    loss = -delta.clip(upper=0)

    rs = gain.rolling(14).mean() / loss.rolling(14).mean()
    return 100 - (100 / (1 + rs))

# ---------- AI ----------
def ai_analysis(symbol, price, trend):
    try:
        res = client.chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=[{
                "role": "user",
                "content": f"Analyze {symbol}. Price {price}, Trend {trend}. Give short buy/sell suggestion."
            }]
        )
        return res.choices[0].message.content
    except:
        return "AI unavailable"

# ---------- CHART IMAGES ----------
def generate_chart_images(data):
    paths = []

    plt.figure()
    data["Close"].plot(title="Closing Price")
    p1 = "price.png"
    plt.savefig(p1)
    paths.append(p1)
    plt.close()

    plt.figure()
    data["Volume"].plot(title="Volume")
    p2 = "volume.png"
    plt.savefig(p2)
    paths.append(p2)
    plt.close()

    plt.figure()
    data[["Close", "MA"]].plot(title="Moving Average")
    p3 = "ma.png"
    plt.savefig(p3)
    paths.append(p3)
    plt.close()

    plt.figure()
    data["RSI"].plot(title="RSI")
    p4 = "rsi.png"
    plt.savefig(p4)
    paths.append(p4)
    plt.close()

    return paths

# ---------- PROFESSIONAL PDF ----------
def create_stock_pdf(symbol, price, rsi, trend, insight, image_paths):
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "TitleStyle",
        parent=styles["Title"],
        textColor=colors.darkblue,
        alignment=1
    )

    heading_style = ParagraphStyle(
        "HeadingStyle",
        parent=styles["Heading2"],
        textColor=colors.darkgreen
    )

    normal_style = styles["Normal"]

    content = []

    # TITLE
    content.append(Paragraph(f"📊 Stock Analysis Report: {symbol}", title_style))
    content.append(Spacer(1, 20))

    # SUMMARY TABLE
    table_data = [
        ["Metric", "Value"],
        ["Current Price", f"${price:.2f}"],
        ["RSI", f"{rsi:.2f}"],
        ["Trend", trend]
    ]

    table = Table(table_data, colWidths=[150, 200])

    table.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), colors.grey),
        ("TEXTCOLOR",(0,0),(-1,0),colors.white),
        ("GRID", (0,0), (-1,-1), 1, colors.black),
        ("BACKGROUND", (0,1), (-1,-1), colors.beige)
    ]))

    content.append(Paragraph("📌 Summary", heading_style))
    content.append(Spacer(1, 10))
    content.append(table)
    content.append(Spacer(1, 20))

    # AI INSIGHT
    content.append(Paragraph("🤖 AI Recommendation", heading_style))
    content.append(Spacer(1, 10))
    content.append(Paragraph(insight, normal_style))
    content.append(Spacer(1, 20))

    # RSI INTERPRETATION
    if rsi > 70:
        rsi_text = "The stock is overbought. Price may fall."
    elif rsi < 30:
        rsi_text = "The stock is oversold. Price may rise."
    else:
        rsi_text = "The stock is neutral."

    content.append(Paragraph("📊 RSI Analysis", heading_style))
    content.append(Spacer(1, 10))
    content.append(Paragraph(rsi_text, normal_style))
    content.append(Spacer(1, 20))

    # CHARTS
    content.append(Paragraph("📈 Visual Analysis", heading_style))
    content.append(Spacer(1, 15))

    for path in image_paths:
        content.append(Image(path, width=400, height=250))
        content.append(Spacer(1, 15))

    # FOOTER
    content.append(Spacer(1, 20))
    content.append(Paragraph(
        "Generated by AI Business Platform",
        ParagraphStyle("footer", alignment=1, textColor=colors.grey)
    ))

    doc.build(content)
    buffer.seek(0)

    return buffer

# ---------- UI ----------
def stock_ui():
    st.title("📊 Smart Stock Analyzer")

    q = st.text_input("🔍 Search Company")

    ticker = None

    if q:
        results = search_tickers(q)

        if results:
            opts = [f"{i['description']} ({i['symbol']})" for i in results]
            sel = st.selectbox("Select Company", opts)
            ticker = sel.split("(")[-1].replace(")", "")
        else:
            st.warning("No results")

    if ticker:
        start = st.date_input("Start", date(2023,1,1))
        end = st.date_input("End", date.today())

        data = yf.Ticker(ticker).history(start=start, end=end)

        if data.empty:
            st.warning("No data")
            return

        # CALCULATIONS
        data["MA"] = data["Close"].rolling(20).mean()
        data["RSI"] = calculate_rsi(data)

        price = data["Close"].iloc[-1]
        prev = data["Close"].iloc[-2]
        rsi = data["RSI"].iloc[-1]

        trend = "Uptrend" if price > data["Close"].mean() else "Downtrend"

        # UI
        st.metric("💰 Price", f"${price:.2f}", f"{price-prev:.2f}")

        st.line_chart(data["Close"])
        st.line_chart(data["Volume"])
        st.line_chart(data[["Close","MA"]])
        st.line_chart(data["RSI"])

        # AI
        st.subheader("🤖 AI Insight")
        insight = ai_analysis(ticker, price, trend)
        st.success(insight)

        # REPORT
        image_paths = generate_chart_images(data)

        pdf = create_stock_pdf(
            ticker,
            price,
            rsi,
            trend,
            insight,
            image_paths
        )

        st.download_button(
            "📄 Download Professional Report",
            pdf,
            file_name=f"{ticker}_report.pdf"
        )

    else:
        st.info("Start typing to search company")